version: '3'

services:
  sing-box:
    container_name: my-sing-box
    # image: ghcr.io/sagernet/sing-box:v1.6.0
    image: gzxhwq/sing-box:v1.6.2
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./config/config.json:/etc/sing-box/config.json
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun